version: '3'

networks:
  my_network2:
    driver: bridge

volumes:
  volume_postgres:

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestion_abonnement
    ports:
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    networks:
      - my_network2

  spring-app:
    image: kaoutarbelah/csca_projet_fr_bk_spring-app
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my_network2
